### ISSUE TITLE
Update server list problem with mullvad

### ISSUE THREAD

**Issue by Punkado** [corrad1nho/qomui#100]
Since some days, i am not able to download or update the server list with the Mullvad provider:

```
2019-06-04 18:26:27,682 - INFO - Downloading certificates for Mullvad
2019-06-04 18:26:27,684 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2019-06-04 18:26:27,784 - DEBUG - https://raw.githubusercontent.com:443 "GET /mullvad/mullvadvpn-app/master/dist-assets/ca.crt HTTP/1.1" 200 1632
2019-06-04 18:26:27,810 - DEBUG - https://raw.githubusercontent.com:443 "GET /mullvad/mullvadvpn-app/master/dist-assets/api_root_ca.pem HTTP/1.1" 200 939
2019-06-04 18:26:27,814 - DEBUG - Starting new HTTPS connection (1): www.mullvad.net:443
2019-06-04 18:26:28,115 - DEBUG - https://www.mullvad.net:443 "GET /en/servers/ HTTP/1.1" 200 None
2019-06-04 18:26:28,117 - INFO - Fetching server list for Mullvad

```

**Comment by palmsiberia** [comment]
Hi,

I got the exact same here:

2019-06-09 14:43:16,605 - INFO - Downloading certificates for Mullvad
2019-06-09 14:43:16,613 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2019-06-09 14:43:16,712 - DEBUG - https://raw.githubusercontent.com:443 "GET /mullvad/mullvadvpn-app/master/dist-assets/ca.crt HTTP/1.1" 200 1632
2019-06-09 14:43:16,733 - DEBUG - https://raw.githubusercontent.com:443 "GET /mullvad/mullvadvpn-app/master/dist-assets/api_root_ca.pem HTTP/1.1" 200 939
2019-06-09 14:43:16,739 - DEBUG - Starting new HTTPS connection (1): www.mullvad.net:443
2019-06-09 14:43:16,980 - DEBUG - https://www.mullvad.net:443 "GET /en/servers/ HTTP/1.1" 200 None
2019-06-09 14:43:16,984 - INFO - Fetching server list for Mullvad

Tried it with protonvpn and that did work.

**Comment by RealOrangeOne** [comment]
I've got the same issue. I tried looking at the `qomui.service` logs, and I think i've found the root cause:

```
Jun 09 15:47:52 *** python[3658]: Traceback (most recent call last):
                                          File "/usr/lib/python3.7/site-packages/qomui/update.py", line 74, in run
                                            getattr(self, self.provider.lower())()
                                          File "/usr/lib/python3.7/site-packages/qomui/update.py", line 304, in mullvad
                                            for entry in server_parse[0].find_all('tr'):
                                        IndexError: list index out of range

I assume mullvad changed the structure of the page `qomui` crawls to fetch the required data.

**Comment by GalaxyCurse** [comment]
Same issue for me. Was mainly testing qomui for the bypass feature, since I still haven't managed to access my local LAN when connected to Mullvad Wireguard. The official MacOS app have a checkbox to allow local LAN and it works perfectly, but when trying to copy the "AllowedIPs over to my Linux box's wg-quick script, it didn't work, so I hoped I could use this to bypass a browser and and a few apps. But the Mullvad download bug seems to stop me and I haven't found any way to manually add or import a server in qumui yet.
