### ISSUE TITLE
"Qomui-service is not available" when trying to import Mullvad configs through GUI

### ISSUE THREAD

**Issue by pemyunupa** [corrad1nho/qomui#115]
`sudo systemctl status qomui.service 
● qomui.service - qomui
   Loaded: loaded (/usr/lib/systemd/system/qomui.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Wed 2019-08-07 18:34:03 EEST; 12s ago
  Process: 21944 ExecStart=/usr/bin/env qomui-service (code=killed, signal=ABRT)
 Main PID: 21944 (code=killed, signal=ABRT)

Aug 07 18:33:29 Z390 systemd[1]: Starting qomui...
Aug 07 18:33:30 Z390 systemd[1]: Started qomui.
Aug 07 18:33:30 Z390 env[21944]: openvpn: no process found
Aug 07 18:33:30 Z390 env[21944]: net.ipv6.conf.all.disable_ipv6 = 0
Aug 07 18:34:02 Z390 python[21944]: Traceback (most recent call last):
                                      File "/usr/lib/python3.7/site-packages/qomui/update.py", line 74, in run
                                        getattr(self, self.provider.lower())()
                                      File "/usr/lib/python3.7/site-packages/qomui/update.py", line 304, in mullvad
                                        for entry in server_parse[0].find_all('tr'):
                                    IndexError: list index out of range`

**Comment by pemyunupa** [comment]
qomui log
```

2019-08-07 18:43:26,889 - DEBUG - Successfully connected to qomui-service via DBus
2019-08-07 18:43:26,899 - INFO - Qomui version 0.8.2
2019-08-07 18:43:26,900 - WARNING - [Errno 2] No such file or directory: '/usr/share/qomui/config.json': Could not open /usr/share/qomui/config.json
2019-08-07 18:43:26,900 - WARNING - [Errno 2] No such file or directory: '/root/.qomui/protocol.json': Could not open /root/.qomui/protocol.json
2019-08-07 18:43:26,900 - WARNING - [Errno 2] No such file or directory: '/root/.qomui/bypass_apps.json': Could not open /root/.qomui/bypass_apps.json
2019-08-07 18:43:26,901 - WARNING - [Errno 2] No such file or directory: '/root/.qomui/profile.json': Could not open /root/.qomui/profile.json
2019-08-07 18:43:26,901 - INFO - Loading default configuration
2019-08-07 18:43:26,902 - INFO - Total number of server: 0
2019-08-07 18:43:26,928 - ERROR - Could not identify default gateway for ipv6 - no network connectivity
2019-08-07 18:43:26,928 - INFO - Detected new network connection
2019-08-07 18:43:26,935 - WARNING - iptables: failed to apply ['-t', 'mangle', '-D', 'OUTPUT', '-m', 'cgroup', '--cgroup', '0x00110011', '-j', 'MARK', '--set-mark', '11']
2019-08-07 18:43:26,938 - WARNING - iptables: failed to apply ['-t', 'nat', '-D', 'POSTROUTING', '-m', 'cgroup', '--cgroup', '0x00110011', '-o', 'enp5s0', '-j', 'MASQUERADE']
2019-08-07 18:43:26,941 - WARNING - iptables: failed to apply ['-D', 'OUTPUT', '-m', 'cgroup', '--cgroup', '0x00110011', '-j', 'ACCEPT']
2019-08-07 18:43:26,944 - WARNING - iptables: failed to apply ['-D', 'INPUT', '-m', 'cgroup', '--cgroup', '0x00110011', '-j', 'ACCEPT']
2019-08-07 18:43:26,947 - WARNING - iptables: failed to apply ['-t', 'nat', '-D', 'OUTPUT', '-m', 'cgroup', '--cgroup', '0x00110011', '-p', 'tcp', '--dport', '53', '-j', 'REDIRECT', '--to-ports', '5354']
2019-08-07 18:43:26,950 - WARNING - iptables: failed to apply ['-t', 'nat', '-D', 'OUTPUT', '-m', 'cgroup', '--cgroup', '0x00110011', '-p', 'udp', '--dport', '53', '-j', 'REDIRECT', '--to-ports', '5354']
2019-08-07 18:43:26,953 - WARNING - iptables: failed to apply ['-t', 'mangle', '-D', 'OUTPUT', '-m', 'cgroup', '--cgroup', '0x00110011', '-j', 'MARK', '--set-mark', '11']
2019-08-07 18:43:26,956 - WARNING - iptables: failed to apply ['-t', 'nat', '-D', 'POSTROUTING', '-m', 'cgroup', '--cgroup', '0x00110011', '-o', 'enp5s0', '-j', 'MASQUERADE']
2019-08-07 18:43:26,959 - WARNING - iptables: failed to apply ['-D', 'OUTPUT', '-m', 'cgroup', '--cgroup', '0x00110011', '-j', 'ACCEPT']
2019-08-07 18:43:26,962 - WARNING - iptables: failed to apply ['-D', 'INPUT', '-m', 'cgroup', '--cgroup', '0x00110011', '-j', 'ACCEPT']
2019-08-07 18:43:26,965 - WARNING - iptables: failed to apply ['-t', 'nat', '-D', 'OUTPUT', '-m', 'cgroup', '--cgroup', '0x00110011', '-p', 'tcp', '--dport', '53', '-j', 'REDIRECT', '--to-ports', '5354']
2019-08-07 18:43:26,969 - WARNING - iptables: failed to apply ['-t', 'nat', '-D', 'OUTPUT', '-m', 'cgroup', '--cgroup', '0x00110011', '-p', 'udp', '--dport', '53', '-j', 'REDIRECT', '--to-ports', '5354']
2019-08-07 18:43:26,969 - INFO - Deleted cgroup
```

**Comment by zurp** [comment]
I'm having the same issue.
Log:
```
INFO - Downloading certificates for Mullvad
INFO - Fetching server list for Mullvad
```

```
xxx systemd[1]: Starting qomui...
xxx systemd[1]: Started qomui.
xxx env[16032]: openvpn: no process found
xxx env[16032]: net.ipv6.conf.all.disable_ipv6 = 1
xxx env[16032]: Error: argument "bypass_qomui" is wrong: invalid table ID
xxx python[16032]: Traceback (most recent call last):
                                      File "/usr/lib/python3.7/site-packages/qomui/update.py", line 74, in run
                                        getattr(self, self.provider.lower())()
                                      File "/usr/lib/python3.7/site-packages/qomui/update.py", line 304, in mullvad
                                        for entry in server_parse[0].find_all('tr'):
                                    IndexError: list index out of range
xxx systemd[1]: qomui.service: Main process exited, code=killed, status=6/ABRT
xxx systemd[1]: qomui.service: Failed with result 'signal'.
```

**Comment by Farcrada** [comment]
Pull request: https://github.com/corrad1nho/qomui/pull/110 will fix this, probably waiting for a push to live (from develop).

If you want you can apply the patch yourself.
