### ISSUE TITLE
Crash caused by certificates when importing Mullvad

### ISSUE THREAD

**Issue by Farcrada** [corrad1nho/qomui#118]
```
systemctl status qomui
● qomui.service - qomui
   Loaded: loaded (/usr/lib/systemd/system/qomui.service; disabled; vendor preset: enabled)
   Active: failed (Result: signal) since Fri 2019-09-06 17:43:30 CEST; 9s ago
  Process: 9780 ExecStart=/usr/bin/env qomui-service (code=killed, signal=ABRT)
 Main PID: 3567 (code=killed, signal=ABRT)

Sep 06 17:43:30 farcrada env[5372]: Traceback (most recent call last):
Sep 06 17:43:30 farcrada env[5372]:   File "/usr/lib/python3.6/site-packages/qomui/update.py", line 74, in run
Sep 06 17:43:30 farcrada env[5372]:     getattr(self, self.provider.lower())()
Sep 06 17:43:30 farcrada env[5372]:   File "/usr/lib/python3.6/site-packages/qomui/update.py", line 405, in mullvad
Sep 06 17:43:30 farcrada env[5372]:     self.copy_certs(self.provider)
Sep 06 17:43:30 farcrada env[5372]:   File "/usr/lib/python3.6/site-packages/qomui/update.py", line 1083, in copy_certs
Sep 06 17:43:30 farcrada env[5372]:     for f in os.listdir(self.temp_path):
Sep 06 17:43:30 farcrada env[5372]: FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/qomui/temp/Mullvad'
Sep 06 17:43:30 farcrada systemd[1]: qomui.service: Main process exited, code=killed, status=6/ABRT
Sep 06 17:43:30 farcrada systemd[1]: qomui.service: Failed with result 'signal'.
```

I figure a simple try catch should fix this, but I don't know. This is mainly just a major bother; all things considered.

**Comment by yochananmarqos** [comment]
I'm having a similar issue, but it's a show stopper here. I just built from the latest commit and cannot import Mullvad servers at all. Therefore the program is useless at this point.

```
$ systemctl status qomui.service 
● qomui.service - qomui
   Loaded: loaded (/usr/lib/systemd/system/qomui.service; disabled; vendor preset: disabled)
   Active: failed (Result: signal) since Tue 2019-09-10 13:09:41 MDT; 15s ago
  Process: 112062 ExecStart=/usr/bin/env qomui-service (code=killed, signal=ABRT)
 Main PID: 112062 (code=killed, signal=ABRT)

Sep 10 13:09:07 inspirognome systemd[1]: Starting qomui...
Sep 10 13:09:07 inspirognome systemd[1]: Started qomui.
Sep 10 13:09:07 inspirognome env[112062]: openvpn: no process found
Sep 10 13:09:07 inspirognome env[112062]: net.ipv6.conf.all.disable_ipv6 = 0
Sep 10 13:09:23 inspirognome env[112062]: Error: argument "bypass_qomui" is wrong: invalid table ID
Sep 10 13:09:41 inspirognome python[112062]: Traceback (most recent call last):
                                               File "/usr/lib/python3.7/site-packages/qomui/update.py", line 74, in run
                                                 getattr(self, self.provider.lower())()
                                               File "/usr/lib/python3.7/site-packages/qomui/update.py", line 304, in mullvad
                                                 for entry in server_parse[0].find_all('tr'):
                                             IndexError: list index out of range
Sep 10 13:09:41 inspirognome systemd[1]: qomui.service: Main process exited, code=killed, status=6/ABRT
Sep 10 13:09:41 inspirognome systemd[1]: qomui.service: Failed with result 'signal'.
```
