### ISSUE TITLE
Ubuntu 20.04 qomui-gui 0.8.3 crash when minimized

### ISSUE THREAD

**Issue by skaox** [corrad1nho/qomui#143]
Hi,

when I launch qomui-gui in terminal :
QLayout: Attempting to add QLayout "" to QWidget "statusTab", which already has a layout
QLayout: Attempting to add QLayout "" to QomuiGui "Form", which already has a layout

When I try to close qomui-gui a new small window appear with a countdown and if I select Minimize it crash :
QXcbConnection: XCB error: 3 (BadWindow), sequence: 791, resource id: 11132278, major code: 40 (TranslateCoords), minor code: 0

**I only use wireguard but when Minimize crash wg_qomui is still connected (wg show) until I launch it another time.**

Thank you in advance

Ubuntu mate 18.04.4 x64
Mate 1.20.1
Qomui 0.8.3

**Comment by skaox** [comment]
I've updated my system to Ubuntu Mate 20.04 (MATE 1.24.0), Qomui 0.8.3 and now :

qomui-gui 

`
Traceback (most recent call last):
  File "/usr/bin/qomui-gui", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'qomui==0.8.3' distribution was not found and is required by the application`

THANK YOU in advance !

**Comment by skaox** [comment]
For Ubuntu 20.04 thx to sr0wpgxb6g answer is in this post https://github.com/corrad1nho/qomui/issues/144

apt install python3-psutil python3-pexpect python3-qtpy python3-dbus.mainloop.pyqt5
and install qomui_0.8.3_amd64.deb normally with GDebi.

Bug still there when I want to minimize qomui-gui window but it's working when I use systray icon to minimize it.

In terminal when it crash :
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 887, resource id: 11496037, major code: 40 (TranslateCoords), minor code: 0

**Comment by skaox** [comment]
For Ubuntu 20.04 thx to sr0wpgxb6g answer is in this post #144

apt install python3-psutil python3-pexpect python3-qtpy python3-dbus.mainloop.pyqt5

then install qomui_0.8.3_amd64.deb normally.

Bug still there when qomui-gui is minimized with the main windows but it's working when I use systray icon.

In terminal when it crash :
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 887, resource id: 11496037, major code: 40 (TranslateCoords), minor code: 0

In qomui-gui (debug) :
ERROR - Import Error: QtWebEngine is not available

**Comment by skaox** [comment]
For Ubuntu 20.04 (Mate) THX to sr0wpgxb6g for his answer in this post #144

Download the source and run :

chmod +x setup.py
sudo ./setup.py install

sudo apt install python3-psutil python3-pexpect python3-qtpy python3-dbus.mainloop.pyqt5

Remove qomui with synaptic and install qomui_0.8.3_amd64.deb with GDebi for ex.
who will complete the install of :
dnsmasq geoip-bin geoip-database libgeoip1 libnetaddr-ip-perl libsocket6-perl net-tools python3-bs4 python3-html5lib python3-lxml python3-soupsieve python3-webencodings stunnel4

On Ubuntu 20.04 dnsmasq will not work because it is in conflict with systemd-resolved.

**Bug still there when qomui-gui is minimized with the main windows but it's working when systray icon is used.**

Sometimes in terminal when it crash :
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 887, resource id: 11496037, major code: 40 (TranslateCoords), minor code: 0


## UPDATE ##

Not sure you need source after :

apt install wireguard openvpn resolvconf dnsmasq dnsutils net-tools stunnel4 geoip-bin geoip-database libgeoip1 libnetaddr-ip-perl libsocket6-perl cgroup-tools python3-psutil python3-setuptools python3-pexpect python3-qtpy python3-pyqt5 python3-dbus python3-dbus.mainloop.pyqt5 python3-requests python3-lxml python3-bs4 python3-cryptography python3-soupsieve python3-webencodings python3-bs4 python3-html5lib python3-lxml

**Comment by skaox** [comment]
For Ubuntu 20.04 (Mate) THX to sr0wpgxb6g for his answer in this post #144

Download the source and run :

chmod +x setup.py
sudo ./setup.py install

sudo apt install python3-psutil python3-pexpect python3-qtpy python3-dbus.mainloop.pyqt5

Remove qomui with synaptic and install qomui_0.8.3_amd64.deb with GDebi for ex.
who will complete the install of :
dnsmasq geoip-bin geoip-database libgeoip1 libnetaddr-ip-perl libsocket6-perl net-tools python3-bs4 python3-html5lib python3-lxml python3-soupsieve python3-webencodings stunnel4

On Ubuntu 20.04 dnsmasq will not work because it is in conflict with systemd-resolved.

**Bug still there when qomui-gui is minimized with the main windows but it's working when systray icon is used.**

Sometimes in terminal when it crash :
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 887, resource id: 11496037, major code: 40 (TranslateCoords), minor code: 0


## UPDATE ##

Not sure you need source :

apt install wireguard openvpn resolvconf dnsmasq dnsutils net-tools stunnel4 geoip-bin geoip-database libgeoip1 libnetaddr-ip-perl libsocket6-perl cgroup-tools python3-psutil python3-setuptools python3-pexpect python3-qtpy python3-pyqt5 python3-dbus python3-dbus.mainloop.pyqt5 python3-requests python3-lxml python3-bs4 python3-cryptography python3-soupsieve python3-webencodings python3-bs4 python3-html5lib python3-lxml

**Comment by skaox** [comment]
For Ubuntu 20.04 (Mate) THX to sr0wpgxb6g for his answer in this post #144

Download the source and run :

chmod +x setup.py
sudo ./setup.py install

sudo apt install python3-psutil python3-pexpect python3-qtpy python3-dbus.mainloop.pyqt5

Remove qomui with synaptic and install qomui_0.8.3_amd64.deb with GDebi for ex.
who will complete the install of :
dnsmasq geoip-bin geoip-database libgeoip1 libnetaddr-ip-perl libsocket6-perl net-tools python3-bs4 python3-html5lib python3-lxml python3-soupsieve python3-webencodings stunnel4

On Ubuntu 20.04 dnsmasq will not work because it is in conflict with systemd-resolved.

**Bug still there when qomui-gui is minimized with the main windows but it's working when systray icon is used.**

Sometimes in terminal when it crash :
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 887, resource id: 11496037, major code: 40 (TranslateCoords), minor code: 0


## UPDATE ##

apt install wireguard openvpn resolvconf dnsmasq dnsutils net-tools stunnel4 geoip-bin geoip-database libgeoip1 libnetaddr-ip-perl libsocket6-perl cgroup-tools python3-psutil python3-setuptools python3-pexpect python3-qtpy python3-pyqt5 python3-pyqt5.qtwebengine python3-dbus python3-dbus.mainloop.pyqt5 python3-requests python3-lxml python3-bs4 python3-cryptography python3-soupsieve python3-webencodings python3-bs4 python3-html5lib python3-lxml
