### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'qomui==0.8.3' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by carlespla** [corrad1nho/qomui#144]
Fedora 32

**Comment by skaox** [comment]
Same here on Ubuntu Mate 20.04 :

qomui-gui

`
Traceback (most recent call last):
  File "/usr/bin/qomui-gui", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'qomui==0.8.3' distribution was not found and is required by the application`

**Comment by sr0wpgxb6g** [comment]
I'm getting the same error on Ubuntu 20.04. I think changes in 20.04 broke the package.

Download the source, run "sudo setup.py install" and then install these packages: "python3-psutil python3-pexpect python3-qtpy python3-dbus.mainloop.pyqt5". After that it works fine. Hopefully the package will get updated.

**Comment by skaox** [comment]
Manual install with
apt install python3-psutil python3-pexpect python3-qtpy python3-dbus.mainloop.pyqt5
install from source with setup.py didn't work correctly for me (systray icon was missing, maybe more) so I delete it with Synaptic and used qomui_0.8.3_amd64.deb with GDebi who complete the install of 4-5 missing packages (geoip, ...) et voilà ;-!
A big THANK YOU @sr0wpgxb6g  :+1:

**Comment by skaox** [comment]
For Ubuntu 20.04 (Mate)

Download the source and run :

chmod +x setup.py
sudo ./setup.py install
sudo apt install python3-psutil python3-pexpect python3-qtpy python3-dbus.mainloop.pyqt5

After that I remove qomui with Synaptic and install qomui_0.8.3_amd64.deb with GDebi
who will complete the install of :
dnsmasq geoip-bin geoip-database libgeoip1 libnetaddr-ip-perl libsocket6-perl net-tools python3-bs4 python3-html5lib python3-lxml python3-soupsieve python3-webencodings stunnel4

On Ubuntu 20.04 dnsmasq will not work because is in conflict with systemd-resolved.

Voilà ;-!

Bug still there when qomui-gui is minimized with the main windows but it's working when I use systray icon.

A big THANK YOU sr0wpgxb6g  :+1:

**Comment by ofit** [comment]
The same bug on ubuntu 20.04.

```
pavel@Lenovo-G580:~$ qomui-gui
Traceback (most recent call last):
  File "/usr/bin/qomui-gui", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'qomui==0.8.3' distribution was not found and is required by the application
```

**Comment by oatmealm** [comment]
Is there a simple solution for this problem for Fedora 34?
