### ISSUE TITLE
am on ARCH, i get this when i try to set the provider

### ISSUE THREAD

**Issue by iqzer0** [corrad1nho/qomui#145]
Automatic download is available for the following providers: Airvpn, Mullvad, PIA, Windscribe and ProtonVPN
Please enter your credentials
Enter account number:
1234123
Please wait....
Traceback (most recent call last):
  File "/usr/bin/qomui-cli", line 11, in <module>
    load_entry_point('qomui==0.8.2', 'console_scripts', 'qomui-cli')()
  File "/usr/lib/python3.8/site-packages/qomui/qomui_cli.py", line 438, in main
    ex = QomuiCli(args=args)
  File "/usr/lib/python3.8/site-packages/qomui/qomui_cli.py", line 52, in __init__
    self.arguments(self.args)
  File "/usr/lib/python3.8/site-packages/qomui/qomui_cli.py", line 183, in arguments
    self.add_server(provider)
  File "/usr/lib/python3.8/site-packages/qomui/qomui_cli.py", line 253, in add_server
    self.qomui_service.import_thread(credentials)
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.KeyError: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.8/site-packages/qomui/qomui_service.py", line 363, in import_thread
    return provider
  File "/usr/lib/python3.8/site-packages/qomui/qomui_service.py", line 366, in start_import_thread
    def imported(self, result):
  File "/usr/lib/python3.8/site-packages/qomui/update.py", line 57, in __init__
    self.allowed_ips = []
KeyError: 'update'

**Comment by Ph0rk0z** [comment]
Did you build it from the AUR? I did and downloaded protn configs just fine.

**Comment by cauebs** [comment]
I built it from AUR and get the same error when trying to add a provider from an OpenVPN file.
