### ISSUE TITLE
do not work on ubuntu 20.04

### ISSUE THREAD

**Issue by ofit** [corrad1nho/qomui#148]
do not work on ubuntu 20.04

```
pavel@Lenovo-G580:~$ qomui-gui
Traceback (most recent call last):
  File "/usr/bin/qomui-gui", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'qomui==0.8.3' distribution was not found and is required by the application
```

**Comment by ofit** [comment]
The same bug with ticket [pkg_resources.DistributionNotFound: The 'qomui==0.8.3' distribution was not found and is required by the application #144](https://github.com/corrad1nho/qomui/issues/144)
