### ISSUE TITLE
AttributeError: 'QomuiGui' object has no attribute 'initalize_service'. Did you mean: 'initialize_service'?

### ISSUE THREAD

**Issue by AA1999** [corrad1nho/qomui#154]
Running the gui results in this error.
I was prompted an option to enable/start/close the service and I chose enable
```
➜  ~ qomui-gui
QLayout: Attempting to add QLayout "" to QWidget "statusTab", which already has a layout
QLayout: Attempting to add QLayout "" to QomuiGui "Form", which already has a layout
DBus Error: Qomui-Service is currently not available
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.qomui.service': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qomui/qomui_gui.py", line 105, in __init__
    self.qomui_dbus = self.dbus.get_object('org.qomui.service', '/org/qomui/service')
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.10/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.qomui.service was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qomui-gui", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/qomui/qomui_gui.py", line 2748, in main
    ex = QomuiGui()
  File "/usr/lib/python3.10/site-packages/qomui/qomui_gui.py", line 121, in __init__
    self.initalize_service("enable", "--now")
AttributeError: 'QomuiGui' object has no attribute 'initalize_service'. Did you mean: 'initialize_service'?
```

**Comment by Ph0rk0z** [comment]
https://github.com/corrad1nho/qomui/pull/153

**Comment by TournelHenry** [comment]
Yeah. It seems somewhere in the building or coding of the software, the file at `/usr/local/lib/python3.10/dist-packages/qomui/qomui_gui.py` was created with a misspelling. Code was written as "initalize" instead of "intialize".
I was able to simply edit the file with `nano /usr/local/lib/python3.10/dist-packages/qomui/qomui_gui.py` and correct the spelling at those lines. It's around Line 121. Now it works. I'm not knowledgeable enough to fix the root issue with the source code. So, anytime I update or re-install the software, I'll have to re-apply  that fix LOL.
