### ISSUE TITLE
`IndexError: list index out of range` crash on latest qomui and mullvad

### ISSUE THREAD

**Issue by sudokit** [corrad1nho/qomui#156]
Im using solus linux with kernel 5.13.1-187.current and latest qomui version trying to download the mullvad provider. i get this error in qomui.service logs:
```
× qomui.service - qomui
     Loaded: loaded (/usr/lib/systemd/system/qomui.service; enabled; preset: enabled)
     Active: failed (Result: signal) since Wed 2023-04-19 21:46:42 EEST; 3s ago
   Duration: 4.258s
    Process: 37400 ExecStart=/usr/bin/env qomui-service (code=killed, signal=ABRT)
   Main PID: 37400 (code=killed, signal=ABRT)
        CPU: 256ms

Apr 19 21:46:37 epinephrine systemd[1]: Starting qomui...
Apr 19 21:46:38 epinephrine systemd[1]: Started qomui.
Apr 19 21:46:38 epinephrine env[37401]: openvpn: no process found
Apr 19 21:46:38 epinephrine env[37404]: net.ipv6.conf.all.disable_ipv6 = 0
Apr 19 21:46:42 epinephrine python3[37400]: Traceback (most recent call last):
                                              File "/usr/lib/python3.10/site-packages/qomui/update.py", line 74, in run
                                                getattr(self, self.provider.lower())()
                                              File "/usr/lib/python3.10/site-packages/qomui/update.py", line 304, in mullvad
                                                for entry in server_parse[0].find_all('tr'):
                                            IndexError: list index out of range
Apr 19 21:46:42 epinephrine systemd[1]: qomui.service: Main process exited, code=killed, status=6/ABRT
Apr 19 21:46:42 epinephrine systemd[1]: qomui.service: Failed with result 'signal'.
```

**Comment by JoeHetro** [comment]
Please note that I am currently out of the office. During this time I will have only episodic access to my emails and replies will take longer than usual and may be less detailed than normal.

**Comment by sudokit** [comment]
Yeah no worries! Any help is greatly appreciated!

**Comment by sudokit** [comment]
Yeah no worries! Any help is greatly appreciated!

**Comment by sudokit** [comment]
This is kinda a duplicate of #115, but that issue is centuries old. Should be fixed in this version.
