### ISSUE TITLE
Ubuntu 16.04 Error

### ISSUE THREAD

**Issue by qazip** [corrad1nho/qomui#3]
Hey there,

I am trying to test your vpn-client but I'm getting the following error:

```
 ~/qomui   master  sudo qomui-gui      
QLayout: Attempting to add QLayout "" to QomuiGui "Form", which already has a layout
DBus Error: Qomui-Service is currently not available
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 607, in msg_reply_handler
    *message.get_args_list()))
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 410, in _introspect_error_handler
    error)
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/usr/local/lib/python3.5/dist-packages/qomui/qomui_gui.py", line 48, in emit
    msg = json.dumps(dict(record.__dict__))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: DBusException(dbus.String('Message recipient disconnected from message bus without replying'),) is not JSON serializable
Traceback (most recent call last):
  File "/usr/local/bin/qomui-gui", line 9, in <module>
    load_entry_point('qomui==0.4.1', 'gui_scripts', 'qomui-gui')()
  File "/usr/local/lib/python3.5/dist-packages/qomui/qomui_gui.py", line 2343, in main
    ex = QomuiGui()
  File "/usr/local/lib/python3.5/dist-packages/qomui/qomui_gui.py", line 161, in __init__
    self.qomui_service.disconnect()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.115 was not provided by any .service files

```

**Comment by corrad1nho** [comment]
Hey, it seems that the background service for qomui has not been started. Upon starting qomui there should have been a dialog to start or enable qomui.service. If not you can either start it via systemd: "sudo systemctl start qomui" or from a terminal with "sudo qomui-service". If that does not work please post your terminal output (after launching with "sudo qomui-service").

**Comment by qazip** [comment]
Hello,
```

sudo qomui-service
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/qomui/qomui_service.py", line 90, in load_firewall
    with open('%s/config.json' % (ROOTDIR), 'r') as c:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/qomui/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/qomui-service", line 9, in <module>
    load_entry_point('qomui==0.4.1', 'console_scripts', 'qomui-service')()
  File "/usr/local/lib/python3.5/dist-packages/qomui/qomui_service.py", line 547, in main
    service = QomuiDbus()
  File "/usr/local/lib/python3.5/dist-packages/qomui/qomui_service.py", line 58, in __init__
    self.load_firewall()
  File "/usr/local/lib/python3.5/dist-packages/qomui/qomui_service.py", line 94, in load_firewall
    self.logger.error('%s: Could not open %s/config.json - loading default configuration' % (e, DIRECTORY))
NameError: name 'DIRECTORY' is not defined
```

**Comment by corrad1nho** [comment]
Sorry, qazip, I made a typo. I have already fixed it. You can either reinstall Qomui . Please uninstall qomui. first ("sudo pip3 uninstall qomui"). Alternative just use "cp /usr/share/qomui/default_config.json /usr/share/qomui/config.json".

**Comment by corrad1nho** [comment]
@qazip: Does it work now?
