### ISSUE TITLE
Main process aborts when trying to connect to Mullvad over OpenVPN account is out of time

### ISSUE THREAD

**Issue by ethanrakoff** [corrad1nho/qomui#36]
When you try to connect to a mullvad server using openvpn and the account has no time on it, the main process aborts with this error:
```
python[376]: Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/qomui/tunnel.py", line 44, in run
  self.openvpn()
File "/usr/lib/python3.7/site-packages/qomui/tunnel.py", line 195, in openvpn
  self.ovpn(path, self.hop, cwd_ovpn)
File "/usr/lib/python3.7/site-packages/qomui/tunnel.py", line 440, in ovpn
  elif line.find('SIGTERM[soft,auth-failure]') != -1 and self.connection_status != 1:
AttributeError: 'TunnelThread' object has no attribute 'connection_status'
systemd[1]: qomui.service: Main process exited, code=killed, status=6/ABRT
systemd[1]: qomui.service: Failed with result 'signal'.

```

**Comment by corrad1nho** [comment]
Qomui shouldn't crash when account is expired. Will be fixed in the next update (planned release mid-november).

**Comment by corrad1nho** [comment]
This has been fixed in the latest release. Qomui won't crash any longer once your Mullvad account expires.
