### ISSUE TITLE
Installing on Fedora

### ISSUE THREAD

**Issue by 2tbwXj46BDbdNBRV79DS** [corrad1nho/qomui#5]
Here are my some outputs im getting when trying to install 

```
sudo pip install ./
Processing /home/gputest/qomui
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/site-packages (from qomui==0.5.1) (4.6.0)
Requirement already satisfied: pexpect in /usr/lib/python2.7/site-packages (from qomui==0.5.1) (4.6.0)
Collecting psutil (from qomui==0.5.1)
  Using cached https://files.pythonhosted.org/packages/51/9e/0f8f5423ce28c9109807024f7bdde776ed0b1161de20b408875de7e030c3/psutil-5.4.6.tar.gz
Collecting pycountry (from qomui==0.5.1)
  Using cached https://files.pythonhosted.org/packages/18/99/a81f1da10070c563450a4ef334622e72fb0b7b74c929fdbed711154d8416/pycountry-18.5.26-py2-none-any.whl
Collecting requests (from qomui==0.5.1)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting lxml (from qomui==0.5.1)
  Using cached https://files.pythonhosted.org/packages/af/09/cdb478d8b0392edd4047c5d1f7e6a1fb5e0e7a2f8f14fcf05c6e9ae9edff/lxml-4.2.3-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: ptyprocess>=0.5 in /usr/lib/python2.7/site-packages (from pexpect->qomui==0.5.1) (0.6.0)
Collecting idna<2.8,>=2.5 (from requests->qomui==0.5.1)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->qomui==0.5.1)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests->qomui==0.5.1)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->qomui==0.5.1)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Installing collected packages: psutil, pycountry, idna, chardet, urllib3, certifi, requests, lxml, qomui
  Running setup.py install for psutil ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1bUZzK/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-LZXC3u/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psaix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_exceptions.py -> build/lib.linux-x86_64-2.7/psutil
    creating build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-2.7/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.linux-x86_64-2.7/psutil/tests
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/psutil
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=546 -DPSUTIL_LINUX=1 -I/usr/include/python2.7 -c psutil/_psutil_common.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_common.o
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1bUZzK/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-LZXC3u/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-1bUZzK/psutil/
```
```
sudo python setup.py install
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/qomui
copying qomui/qomui_gui.py -> build/lib/qomui
copying qomui/firewall.py -> build/lib/qomui
copying qomui/__init__.py -> build/lib/qomui
copying qomui/update.py -> build/lib/qomui
copying qomui/qomui_service.py -> build/lib/qomui
copying qomui/mv_config.py -> build/lib/qomui
copying qomui/bypass.py -> build/lib/qomui
copying qomui/latency.py -> build/lib/qomui
running egg_info
creating qomui.egg-info
writing requirements to qomui.egg-info/requires.txt
writing qomui.egg-info/PKG-INFO
writing top-level names to qomui.egg-info/top_level.txt
writing dependency_links to qomui.egg-info/dependency_links.txt
writing entry points to qomui.egg-info/entry_points.txt
writing manifest file 'qomui.egg-info/SOURCES.txt'
reading manifest file 'qomui.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'qomui.egg-info/SOURCES.txt'
running install_lib
creating /usr/lib/python2.7/site-packages/qomui
copying build/lib/qomui/qomui_gui.py -> /usr/lib/python2.7/site-packages/qomui
copying build/lib/qomui/firewall.py -> /usr/lib/python2.7/site-packages/qomui
copying build/lib/qomui/__init__.py -> /usr/lib/python2.7/site-packages/qomui
copying build/lib/qomui/update.py -> /usr/lib/python2.7/site-packages/qomui
copying build/lib/qomui/qomui_service.py -> /usr/lib/python2.7/site-packages/qomui
copying build/lib/qomui/mv_config.py -> /usr/lib/python2.7/site-packages/qomui
copying build/lib/qomui/bypass.py -> /usr/lib/python2.7/site-packages/qomui
copying build/lib/qomui/latency.py -> /usr/lib/python2.7/site-packages/qomui
byte-compiling /usr/lib/python2.7/site-packages/qomui/qomui_gui.py to qomui_gui.pyc
  File "/usr/lib/python2.7/site-packages/qomui/qomui_gui.py", line 1431
    def filter_servers(self, *arg, display="filter"):
                                         ^
SyntaxError: invalid syntax

byte-compiling /usr/lib/python2.7/site-packages/qomui/firewall.py to firewall.pyc
byte-compiling /usr/lib/python2.7/site-packages/qomui/__init__.py to __init__.pyc
byte-compiling /usr/lib/python2.7/site-packages/qomui/update.py to update.pyc
byte-compiling /usr/lib/python2.7/site-packages/qomui/qomui_service.py to qomui_service.pyc
byte-compiling /usr/lib/python2.7/site-packages/qomui/mv_config.py to mv_config.pyc
byte-compiling /usr/lib/python2.7/site-packages/qomui/bypass.py to bypass.pyc
byte-compiling /usr/lib/python2.7/site-packages/qomui/latency.py to latency.pyc
running install_data
copying resources/qomui.desktop -> /usr/share/applications/
copying resources/qomui.service -> /etc/systemd/system/
copying resources/org.qomui.service.conf -> /etc/dbus-1/system.d/
copying resources/qomui.svg -> /usr/share/icons/hicolor/scalable/apps/
copying resources/qomui_off.svg -> /usr/share/icons/hicolor/scalable/apps/
creating /usr/share/qomui
copying resources/Airvpn_config -> /usr/share/qomui/
copying resources/PIA_config -> /usr/share/qomui/
copying resources/default_config.json -> /usr/share/qomui/
copying resources/firewall_default.json -> /usr/share/qomui/
copying resources/Mullvad_config -> /usr/share/qomui/
copying resources/ssl_config -> /usr/share/qomui/
copying resources/qomui.png -> /usr/share/qomui/
copying resources/hop.sh -> /usr/share/qomui/
copying resources/hop_down.sh -> /usr/share/qomui/
error: can't copy 'resources/VERSION': doesn't exist or not a regular file
```

**Comment by corrad1nho** [comment]
It is a python3 application, so use "sudo pip3 install" or "sudo python3 setup.py install" - your pip-command failed because of an error building the dependency "psutil" - if that persists try "sudo pip3 install --no-deps ./". 

I see that the installation process is tedious and error-prone. Hence, I will provide .rpm/.deb-packages in the future. This will happen very soon, might even manage to do it tonight.

**Comment by 2tbwXj46BDbdNBRV79DS** [comment]
```
sudo pip3 install --no-deps ./
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Processing /home/gputest/qomui
Installing collected packages: qomui
  Running setup.py install for qomui ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-_likxuog-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6uz512q3-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running egg_info
    writing qomui.egg-info/PKG-INFO
    writing dependency_links to qomui.egg-info/dependency_links.txt
    writing entry points to qomui.egg-info/entry_points.txt
    writing requirements to qomui.egg-info/requires.txt
    writing top-level names to qomui.egg-info/top_level.txt
    reading manifest file 'qomui.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'qomui.egg-info/SOURCES.txt'
    running install_lib
    running install_data
    error: can't copy 'resources/VERSION': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-_likxuog-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6uz512q3-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-_likxuog-build/

```

I copyed VERSION file manually to /resoruces and tried again "Successfully installed qomui-0.5.1"

did
$ qomui-gui 
and im got pkg_resources.DistributionNotFound: 

so i did a "sudo dnf install python-lxml"
installed

i continue to get
```

$ qomui-gui
Traceback (most recent call last):
  File "/usr/local/bin/qomui-gui", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'lxml' distribution was not found and is required by qomui


```
doing a $reboot...

**Comment by 2tbwXj46BDbdNBRV79DS** [comment]
okay looks like i just need dependency. proceeding with pycountry..

**Comment by corrad1nho** [comment]
Afaik, pycountry is not available from Fedora repositories, but you can install it via "sudo pip3 install pycountry".

**Comment by 2tbwXj46BDbdNBRV79DS** [comment]
`sudo pip3 install pycountry requests beautifulsoup4 pexpect lxml PyQt5`

`sudo dnf install python3-psutil python3-dbus stunnel`

not sure how to install dbus.mainloop.pyqt5

**Comment by corrad1nho** [comment]
Try "sudo dnf install python3-qt5-base" instead.

**Comment by 2tbwXj46BDbdNBRV79DS** [comment]
We are up and running. Will confirm the steps on my other rig with a fresh Fedora install, and type it up in the readme later... Thanks for the support.
