### ISSUE TITLE
GUI won't start for Ubuntu 16.04 

### ISSUE THREAD

**Issue by poisonowl** [corrad1nho/qomui#67]
Please see my previous comment on issue #53 

I decided I'd give it one more shot installing 0.8.1

I removed and purged the working version 0.7.3 (works fine for me) and then I installed 0.8.1 from the terminal. 

The outline of the GUI only flashes on the screen for 1 second. 

I rebooted, but same issue- GUI only flashes on the screen.

Then I tried to reinstall. Nothing changed. I cannot get the gui to start. 

Perhaps you can see what is wrong. I would really like this to work. 

All the dependencies are installed and current. 

X ~ $ sudo systemctl status qomui  
[sudo] password for X: 
● qomui.service - qomui
   Loaded: loaded (/lib/systemd/system/qomui.service; enabled; vendor preset: en
   Active: active (running) since Fri 2019-01-25 10:07:50 PST; 3min 58s ago
 Main PID: 833 (qomui-service)
   CGroup: /system.slice/qomui.service
           └─833 /usr/bin/python3 /usr/bin/qomui-service

Jan 25 10:07:06  systemd[1]: Starting qomui...
Jan 25 10:07:50  systemd[1]: Started qomui.
Jan 25 10:07:50  env[833]: openvpn: no process found
Jan 25 10:07:50 o env[833]: net.ipv6.conf.all.disable_ipv6 = 
lines 1-11/11 (END)

X ~ $ cat /usr/share/qomui/qomui.log | grep Dbus
2019-01-25 10:03:31,171 - INFO - Dbus-service successfully initialized
2019-01-25 10:07:50,507 - INFO - Dbus-service successfully initialized
2019-01-25 10:10:08,087 - INFO - Dbus-service successfully initialized

X ~ $ qomui-gui
QLayout: Attempting to add QLayout "" to QomuiGui "Form", which already has a layout
Traceback (most recent call last):
  File "/usr/bin/qomui-gui", line 9, in <module>
    load_entry_point('qomui==0.8.1', 'gui_scripts', 'qomui-gui')()
  File "/usr/lib/python3.5/dist-packages/qomui/qomui_gui.py", line 2743, in main
    ex = QomuiGui()
  File "/usr/lib/python3.5/dist-packages/qomui/qomui_gui.py", line 147, in __init__
    self.systemtray()
  File "/usr/lib/python3.5/dist-packages/qomui/qomui_gui.py", line 1112, in systemtray
    self.pop_tray_menu()
  File "/usr/lib/python3.5/dist-packages/qomui/qomui_gui.py", line 1123, in pop_tray_menu
    self.visibility_action = QtWidgets.QAction()
TypeError: arguments did not match any overloaded call:
  QAction(QObject): not enough arguments
  QAction(str, QObject): not enough arguments
  QAction(QIcon, str, QObject): not enough arguments

**Comment by mikeza** [comment]
This issue has been reported and discussed here: https://airvpn.org/topic/26327-alternative-airvpn-client-with-provider-independent-double-hop-support-gnulinux/?p=81843

**Comment by poisonowl** [comment]
Thank you @mikeza :)

**Comment by corrad1nho** [comment]
Yes, unfortunately this bug affects the current release if the Qt version installed on your system is lower than 5.7. I'm working on a fix.

**Comment by poisonowl** [comment]
Installation of 0.8.2 (from deb) is a success!

Prior to installation, removed previous version using: sudo apt-get --purge remove qomui

However, the qomui files in /usr/lib/python3/dist-packages/qomui/__pycache__ were not deleted during the removal, so I removed them separately (the removal had been necessary for previous installations- I will attempt to install on another machine without removing them first and see how that goes).

Thank you for all your hard work!
