### ISSUE TITLE
Can't launch the GUI client

### ISSUE THREAD

**Issue by EKami** [corrad1nho/qomui#91]
Hello,
I'm running arch linux (manjaro) and I installed qomui from aur but when I try to launch the GUI client I get this:
```
Traceback (most recent call last):
  File "/home/ekami/Programs/anaconda3/bin/qomui-gui", line 11, in <module>
    load_entry_point('qomui==0.8.2', 'gui_scripts', 'qomui-gui')()
  File "/home/ekami/Programs/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ekami/Programs/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/ekami/Programs/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/ekami/Programs/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ekami/Programs/anaconda3/lib/python3.7/site-packages/qomui/qomui_gui.py", line 17, in <module>
    from dbus.mainloop.pyqt5 import DBusQtMainLoop
ModuleNotFoundError: No module named 'dbus.mainloop.pyqt5'
```

I can't find the `dbus.mainloop.pyqt5` on pyipy, how can I solve this issue? Thank you.

**Comment by corrad1nho** [comment]
"dbus.mainloop.pyqt5" should be part of python-pyqt5. Can you try re-installing this package?
